# Generated by Django 5.2.2 on 2025-06-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_a', models.CharField(help_text='A short text field, maximum 10 characters.', max_length=10, verbose_name='Field A')),
                ('field_b', models.IntegerField(help_text='An integer value.', verbose_name='Field B')),
                ('number_of_updates', models.IntegerField(default=0, help_text='Counter for the number of times this instance has been modified via the API.', verbose_name='Number of Updates')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Timestamp of the last modification.', verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'Some Model Entry',
                'verbose_name_plural': 'Some Model Entries',
                'ordering': ['-last_modified'],
            },
        ),
    ]
